language: php

php:
  - 5.6
  - 7.2
  - 7.3
  - 7.4
  - nightly

before_script:
  - curl -s http://getcomposer.org/installer | php
  - php composer.phar install --dev

script: phpunit

matrix:
  allowed_failures:
    - php: 7.3
    - php: nightly
